# Generated by Django 4.2.5 on 2023-09-24 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="Name of Role")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Roles",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.role"
            ),
        ),
    ]
